.test:
  stage: test
  image: debian:${RELEASE}
  before_script:
  - echo Etc/UTC > /etc/timezone
  - echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Acquire::Retries "20";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Peer "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Host "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Dpkg::Use-Pty "0";' >> /etc/apt/apt.conf.d/99gitlab
  - apt-get update || true
  - apt-get install -y procps proxychains python3 python3-pytest python3-coverage python3-pytest-cov python3-gnupg python3-bcrypt python3-requests python3-aiohttp python3-openssl python3-pip python3-pyotp
  - sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sysctl -w net.ipv6.conf.default.disable_ipv6=0
  # FIXME: would be nice to resolve proxy.plabs.ch instead of hardcoding one value, or even better to parse http_proxy
  - echo -e "[ProxyList]\nhttp 172.20.0.127 3128\n" > /etc/proxychains.conf
  script:
  # We need to install it otherwise entry points are not accessible by testsuite
  # FIXME: we need to fill loader with static data to make sure our test is reproductible
  # then we won't need that
  - pip3 install --user --editable .
  - proxychains python3 -m pytest --cov=proton --junitxml=report.xml tests/
  - python3-coverage xml -o cov.xml
  artifacts:
    reports:
      cobertura: cov.xml
      junit: report.xml

bandit-sast:
  stage: test
  image: debian:bullseye
  before_script:
  - echo Etc/UTC > /etc/timezone
  - echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Acquire::Retries "20";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Peer "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Host "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Dpkg::Use-Pty "0";' >> /etc/apt/apt.conf.d/99gitlab
  - apt-get update || true
  - apt-get install -y python3 python3-bandit
  - apt-get install -y procps
  - sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sysctl -w net.ipv6.conf.default.disable_ipv6=0
  script:
  # testing the logger require to change environment variable BEFORE the module is loaded => dedicated call
  - bandit proton -r --format xml -o bandit.xml
  artifacts:
    reports:
      junit: bandit.xml



#test-buster:
#  extends: .test
#  variables:
#    RELEASE: 'buster'

test-bullseye:
  extends: .test
  variables:
    RELEASE: 'bullseye'
