.test:
  stage: test
  image: debian:${RELEASE}
  before_script:
  - echo Etc/UTC > /etc/timezone
  - echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Acquire::Retries "20";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Peer "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Host "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Dpkg::Use-Pty "0";' >> /etc/apt/apt.conf.d/99gitlab
  - apt-get update || true
  - apt-get install -y python3 python3-pytest python3-pytest-cov python3-gnupg python3-bcrypt python3-requests python3-aiohttp python3-openssl
  - apt-get install -y procps
  - sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sysctl -w net.ipv6.conf.default.disable_ipv6=0
  script:
  # testing the logger require to change environment variable BEFORE the module is loaded => dedicated call
  - python3 -m pytest --cov=proton --junitxml=report.xml --cov-report xml:cov.xml --cov-report=term tests/
  artifacts:
    reports:
      cobertura: cov.xml
      junit: report.xml

bandit-sast:
  stage: test
  image: debian:bullseye
  before_script:
  - echo Etc/UTC > /etc/timezone
  - echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Acquire::Retries "20";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Peer "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Acquire::https::Verify-Host "false";' >> /etc/apt/apt.conf.d/99gitlab
  - echo 'Dpkg::Use-Pty "0";' >> /etc/apt/apt.conf.d/99gitlab
  - apt-get update || true
  - apt-get install -y python3 python3-bandit
  - apt-get install -y procps
  - sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sysctl -w net.ipv6.conf.default.disable_ipv6=0
  script:
  # testing the logger require to change environment variable BEFORE the module is loaded => dedicated call
  - bandit proton -r --format xml -o bandit.xml
  artifacts:
    reports:
      junit: bandit.xml



test-buster:
  extends: .test
  variables:
    RELEASE: 'buster'

test-bullseye:
  extends: .test
  variables:
    RELEASE: 'bullseye'
